language: android
sudo: false

env:
  - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"

jdk:
  - oraclejdk7

android:
  components:
    - tools
    - android-23
    - build-tools-23.0.1
    - extra-android-m2repository

  licenses:
    - android-sdk-license-.+

script:
  - ./gradlew check --info

notifications:
  slack:
    - secure: "CF/v5lJ7gzYu+X1KnsFG9ijQU4gqi1ooatTt0cZR7Q1z+TUTZrWPQY7I0cWNs322IiV7B+V7Mji++w23tfIKbZ/FPmpSWy31ajl287oj+6WdoenT8PQNdsJy897kPVsgjgPKufN20La2NCorcxlAWpU7h+wfgh1XmtDfCS7US5Nn5WsolWTeS4PyGHKp4Erwnv/cgx2NnJCJrJaP6b1YbhtP/HVjii0Vc/RaujLIdgownTT4jwA4Al6nXD7k4JTFvnFZf35ZbXcQMmeLntJCFzX3tOH12SQ8UbnkK3QrW8iq2pPpf5Wi/CJwGsdpdUSi6+gNn+FwWXo2pvy6xHGiyDhajjvFkqHoQXudg85kbOhmynV6zJCJa7dsbCPI/ikh9Mnq1DbyC2KgMMsZ2lutKFF1E7j+eQjGMAwRzZZ3xqQoavQyU9FosHQioEVurH8bU31Lj5HQAhp21hJh17dF+YJctR0gRzdLUKY/eo5itAvofljFojZjwjLwY3TMfIrXzx0qFPvQBHq42pUNhzWDsIS4hhUkeBVIbiAe+LfBsXDfqXja5kGqSoYHPNcQHXlbte5NJg79shrI41INUNVI8PdhuFrT+jm8kQPlui9CvfkuMAFOSIeockuMz86jNt3bZU80u/mDdrIBVESGlugf16rFqyvz7tgh7C8vR3ypUAY="
