package moe.pine.rxbinding.shared

/**
 * Auto generated
 * Created by CodeGenerator.kt on Apr 3, 2016 10:47:34 AM.
 */
enum class ObservableType {
    AbsListViewScrollEvents,
    AdapterDataChanges,
    AdapterViewItemClickEvents,
    AdapterViewItemClicks,
    AdapterViewItemLongClickEvents,
    AdapterViewItemLongClicks,
    AdapterViewItemSelections,
    AdapterViewSelectionEvents,
    AutoCompleteTextViewItemClickEvents,
    CompoundButtonCheckedChanges,
    MenuItemActionViewEvents,
    MenuItemClicks,
    PopupMenuDismisses,
    PopupMenuItemClicks,
    RadioGroupCheckedChanges,
    RatingBarRatingChangeEvents,
    RatingBarRatingChanges,
    SearchViewQueryTextChangeEvents,
    SearchViewQueryTextChanges,
    SeekBarChangeEvents,
    SeekBarChanges,
    SeekBarSystemChanges,
    SeekBarUserChanges,
    TextViewAfterTextChangeEvents,
    TextViewBeforeTextChangeEvents,
    TextViewEditorActionEvents,
    TextViewEditorActions,
    TextViewTextChangeEvents,
    TextViewTextChanges,
    ToolbarItemClicks,
    ToolbarNavigationClicks,
    ViewAttachEvents,
    ViewAttaches,
    ViewClicks,
    ViewDetaches,
    ViewDrags,
    ViewDraws,
    ViewFocusChanges,
    ViewGlobalLayouts,
    ViewGroupChangeEvents,
    ViewHovers,
    ViewLayoutChangeEvents,
    ViewLayoutChanges,
    ViewLongClicks,
    ViewPreDraws,
    ViewScrollChangeEvents,
    ViewSystemUiVisibilityChanges,
    ViewTouches,
}
